# Generated by Django 5.2.1 on 2025-05-20 06:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
